#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# TODO what happens if the watch command is run during a commit? explosion?

# make sure we are not commiting the current docs folder.
# this way we don't have to make remember to not accidentally stage it.
git reset docs

git checkout docs # make sure the old stuff is stashed to prevent conflicts
git stash --keep-index --include-untracked

npm run clean # clean committed build files before build
npm run deploy
git add docs

npm run clean # prevent a conflict when popping the stash
git stash pop
